name: .NET 7 & Vue.js Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_dotnet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'

    - name: Restore dependencies
      run: dotnet restore src/Calendar.sln

    - name: Build
      run: dotnet build src/Calendar.sln --no-restore

    
    # TODO implement test and run this after
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal

  build_vue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Navigate to Vue.js directory
      run: cd src/Calendar.Web

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Vue.js app
      run: npm run build

    # Optionally, run tests if you have them set up for your Vue project
    - name: Run Vue.js tests
      run: npm run test

